<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.embabel.example</groupId>
        <artifactId>example-agent-parent</artifactId>
        <version>1.5.1-SNAPSHOT</version>
    </parent>
    <groupId>com.embabel.example.java</groupId>
    <artifactId>example-agent-java</artifactId>
    <name>Embabel Agent Java Examples</name>
    <description>Java Examples for Embabel Agentic Flows</description>
    <properties>
        <spring-shell-standard.version>3.4.0</spring-shell-standard.version>
    </properties>


    <dependencies>
        <dependency>
            <groupId>com.embabel.example</groupId>
            <artifactId>examples-common</artifactId>
            <version>${project.version}</version>
        </dependency>

        <!-- Ollama is always included as an option for local model hosting -->
        <dependency>
            <groupId>com.embabel.agent</groupId>
            <artifactId>embabel-agent-starter-ollama</artifactId>
        </dependency>

        <!-- Use Netty Client with Embabel configurable Timeouts -->
        <dependency>
            <groupId>com.embabel.agent</groupId>
            <artifactId>embabel-agent-netty-client-autoconfigure</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.shell</groupId>
            <artifactId>spring-shell-standard</artifactId>
            <version>${spring-shell-standard.version}</version>
        </dependency>

        <!-- Test Dependencies -->
        <dependency>
            <groupId>com.embabel.agent</groupId>
            <artifactId>embabel-agent-test</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
            </plugin>

        </plugins>
    </build>

    <profiles>
        <profile>
            <id>openai-models</id>
            <activation>
                <property>
                    <name>env.OPENAI_API_KEY</name>
                </property>
            </activation>
            <dependencies>
                <dependency>
                    <groupId>com.embabel.agent</groupId>
                    <artifactId>embabel-agent-starter-openai</artifactId>
                </dependency>
            </dependencies>
        </profile>
        <profile>
            <id>anthropic-models</id>
            <activation>
                <property>
                    <name>env.ANTHROPIC_API_KEY</name>
                </property>
            </activation>
            <dependencies>
                <dependency>
                    <groupId>com.embabel.agent</groupId>
                    <artifactId>embabel-agent-starter-anthropic</artifactId>
                </dependency>
            </dependencies>
        </profile>
         <profile>
            <id>bedrock-models</id>
            <activation>
                <property>
                    <name>env.ENABLE_BEDROCK</name>
                </property>
            </activation>
            <dependencies>
                <dependency>
                    <groupId>com.embabel.agent</groupId>
                    <artifactId>embabel-agent-starter-bedrock</artifactId>
                </dependency>
            </dependencies>
        </profile>
        <profile>
            <id>docker-models</id>
            <activation>
                <property>
                    <name>env.ENABLE_DOCKER_MODELS</name>
                </property>
            </activation>
            <dependencies>
                <dependency>
                    <groupId>com.embabel.agent</groupId>
                    <artifactId>embabel-agent-starter-dockermodels</artifactId>
                </dependency>
            </dependencies>
        </profile>
        <profile>
            <id>enable-shell-mcp-client</id>
            <activation>
                <activeByDefault>true</activeByDefault>
            </activation>
            <dependencies>
                <dependency>
                    <groupId>com.embabel.agent</groupId>
                    <artifactId>embabel-agent-starter-shell</artifactId>
                </dependency>
            </dependencies>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.springframework.boot</groupId>
                        <artifactId>spring-boot-maven-plugin</artifactId>
                        <configuration>
                            <mainClass>com.embabel.example.JavaAgentShellApplication</mainClass>
                        </configuration>
                        <version>${spring-boot.version}</version>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <profile>
            <id>enable-shell</id>
            <activation>
                <activeByDefault>false</activeByDefault>
            </activation>
            <dependencies>
                <dependency>
                    <groupId>com.embabel.agent</groupId>
                    <artifactId>embabel-agent-starter-shell</artifactId>
                </dependency>
            </dependencies>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.springframework.boot</groupId>
                        <artifactId>spring-boot-maven-plugin</artifactId>
                        <configuration>
                            <mainClass>com.embabel.example.JavaAgentSimpleShellApplication</mainClass>
                        </configuration>
                        <version>${spring-boot.version}</version>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <profile>
            <id>enable-secured-agent-mcp-server</id>
            <activation>
                <activeByDefault>false</activeByDefault>
            </activation>
            <dependencies>
                <dependency>
                    <groupId>com.embabel.agent</groupId>
                    <artifactId>embabel-agent-starter-mcpserver</artifactId>
                </dependency>
                <dependency>
                    <groupId>com.embabel.agent</groupId>
                    <artifactId>embabel-agent-starter-mcpserver-security</artifactId>
                </dependency>
            </dependencies>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.springframework.boot</groupId>
                        <artifactId>spring-boot-maven-plugin</artifactId>
                        <configuration>
                            <mainClass>com.embabel.example.JavaAgentSecuredMcpServerApplication</mainClass>
                        </configuration>
                        <version>${spring-boot.version}</version>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <profile>
            <id>enable-agent-mcp-server</id>
            <activation>
                <activeByDefault>false</activeByDefault>
            </activation>
            <dependencies>
                <dependency>
                    <groupId>com.embabel.agent</groupId>
                    <artifactId>embabel-agent-starter-mcpserver</artifactId>
                </dependency>
            </dependencies>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.springframework.boot</groupId>
                        <artifactId>spring-boot-maven-plugin</artifactId>
                        <configuration>
                            <mainClass>com.embabel.example.JavaMcpServerApplication</mainClass>
                        </configuration>
                        <version>${spring-boot.version}</version>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <profile>
            <id>enable-agent-a2a-server</id>
            <activation>
                <activeByDefault>false</activeByDefault>
            </activation>
            <dependencies>
                <dependency>
                    <groupId>com.embabel.agent</groupId>
                    <artifactId>embabel-agent-starter-a2a</artifactId>
                </dependency>
            </dependencies>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.springframework.boot</groupId>
                        <artifactId>spring-boot-maven-plugin</artifactId>
                        <configuration>
                            <mainClass>com.embabel.example.JavaA2AServerApplication</mainClass>
                        </configuration>
                        <version>${spring-boot.version}</version>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <profile>
            <id>enable-agent-a2a-server-uber</id>
            <activation>
                <activeByDefault>false</activeByDefault>
            </activation>
            <dependencies>
                <dependency>
                    <groupId>com.embabel.agent</groupId>
                    <artifactId>embabel-agent-starter-a2a</artifactId>
                </dependency>
                <dependency>
                    <groupId>com.embabel.agent</groupId>
                    <artifactId>embabel-agent-starter-openai</artifactId>
                </dependency>
                <dependency>
                    <groupId>com.embabel.agent</groupId>
                    <artifactId>embabel-agent-starter-anthropic</artifactId>
                </dependency>
                <dependency>
                    <groupId>com.embabel.agent</groupId>
                    <artifactId>embabel-agent-starter-bedrock</artifactId>
                </dependency>
            </dependencies>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.springframework.boot</groupId>
                        <artifactId>spring-boot-maven-plugin</artifactId>
                        <configuration>
                            <mainClass>com.embabel.example.JavaA2AContainerApplication</mainClass>
                            <optimizedLaunch>true</optimizedLaunch>
                            <layout>JAR</layout>
                        </configuration>
                        <executions>
                            <execution>
                                <goals>
                                    <goal>repackage</goal>
                                </goals>
                            </execution>
                        </executions>
                        <version>${spring-boot.version}</version>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>

</project>
